### ISSUE TITLE
Spacing between commas and events in Quick Facts is a bit too large 

### ISSUE THREAD

**Issue by moonsdust** [UHSRobotics/UHSRobotics.github.io#16]

**Comment by Ynng** [comment]
This is intended, otherwise the texts gets too close and it gets hard to tell one competition to another.
I think a redesign or rewrite is needed to fix it properly. Stuffing so many bolded, long, competition names in the same sentence was probably not the best idea.

**Comment by Ynng** [comment]
Any ideas?

**Comment by moonsdust** [comment]
I don't have any ideas at the moment but you got a fair point. It's only a minor issue anyways so I don't think it needs to be fixed at the moment.
